services:
  - type: web
    name: api-gateway
    env: docker
    plan: free
    dockerfilePath: ./api_gateway/Dockerfile
    buildContext: ./api_gateway
    envVars:
      - key: NLP_SERVICE_URL
        value: http://nlp-service:8000
      - key: SEARCH_ENGINE_URL
        value: http://search-engine-service:5000
      - key: SCRAPER_SERVICE_URL
        value: http://scraper-service:8001
      - key: PRODUCT_AI_SERVICE_URL
        value: http://product-ai-service:8002
      - key: ENRICHER_SERVICE_URL
        value: http://enrichment-llm-service:8003
  - type: web
    name: nlp-service
    env: docker
    plan: free
    dockerfilePath: ./nlp_service/Dockerfile
    buildContext: ./nlp_service
    envVars:
      - key: GROQ_API_KEY
        sync: false
  - type: web
    name: search-engine-service
    env: docker
    plan: free
    dockerfilePath: ./search-engine-service/Dockerfile
    buildContext: ./search-engine-service
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_SEARCH_ENGINE_ID
        sync: false
  - type: web
    name: scraper-service
    env: docker
    plan: free
    dockerfilePath: ./scraper_service/Dockerfile
    buildContext: ./scraper_service
  - type: web
    name: product-ai-service
    env: docker
    plan: free
    dockerfilePath: ./product_ai_service/Dockerfile
    buildContext: ./product_ai_service
  - type: web
    name: enrichment-llm-service
    env: docker
    plan: free
    dockerfilePath: ./enrichment_llm_service/Dockerfile
    buildContext: ./enrichment_llm_service
    envVars:
      - key: GROQ_API_KEY1
        sync: false